spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: sriraman.nagasubramanian@gmail.com #for testing purpose
    password: pwgolysldlcpoptn
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
  cache:
    type: redis
    redis:
      time-to-live: 300000
  data:
    redis:
      host: localhost
      port: 6379
